additional:
  - "invoice-x12-converter"
  - "nuxt-ucda"

files:
  - "!.gitignore"
  - "!.github/template-sync.yml"
  - "!.pre-commit-config.yaml"
  - "!Makefile"
  - "!.github/dependabot.yml"
  - "!.github/workflows/sync.yaml"
  - "!README.md"
  - "!.roo/"
  - "!.roomodes"
  - "!.taskmasterconfig"
  - "!.windsurfrules"
  - "!scripts/"
  - "!package.json"
  - "!package-lock.json"
  - "!mcp_scripts/pre-commit.hook.template"
  - "!.github/workflows/pre-commit.yaml"
  - "!.github/workflows/dependabot-automerge.yaml"
